"""add citizen progression

Revision ID: 23b2f4cd13f4
Revises: f9cfe17d0390
Create Date: 2026-09-29 15:15:05.687699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b2f4cd13f4'
down_revision: Union[str, Sequence[str], None] = 'f9cfe17d0390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('total_roses', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('citizens', sa.Column('wealth', sa.Integer(), server_default=sa.text('(10)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizens', 'wealth')
    op.drop_column('citizens', 'total_roses')
    # ### end Alembic commands ###
