"""add wood and world tree state

Revision ID: 570bb9372614
Revises: decf8200c69e
Create Date: 2026-10-01 21:24:42.264068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570bb9372614'
down_revision: Union[str, Sequence[str], None] = 'decf8200c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_trees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('tree_key', sa.String(length=100), nullable=False),
    sa.Column('wood_amount', sa.Integer(), server_default=sa.text('(10)'), nullable=False),
    sa.Column('max_wood', sa.Integer(), server_default=sa.text('(10)'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'GROWN'"), nullable=False),
    sa.Column('regrow_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_world_trees_world_tree_key', 'world_trees', ['world_id', 'tree_key'], unique=True)
    op.add_column('citizens', sa.Column('wood', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizens', 'wood')
    op.drop_index('ux_world_trees_world_tree_key', table_name='world_trees')
    op.drop_table('world_trees')
    # ### end Alembic commands ###
