"""add live users and events

Revision ID: decf8200c69e
Revises: f6e7c765008b
Create Date: 2026-09-29 20:07:33.403865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decf8200c69e'
down_revision: Union[str, Sequence[str], None] = 'f6e7c765008b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_live_users_provider_user', 'live_users', ['provider', 'provider_user_id'], unique=True)
    op.create_table('live_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_event_id', sa.String(length=150), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('live_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_minimal', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['live_user_id'], ['live_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_live_events_provider_event', 'live_events', ['provider', 'provider_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_live_events_provider_event', table_name='live_events')
    op.drop_table('live_events')
    op.drop_index('ux_live_users_provider_user', table_name='live_users')
    op.drop_table('live_users')
    # ### end Alembic commands ###
