"""enforce unique citizen per world

Revision ID: f6e7c765008b
Revises: 23b2f4cd13f4
Create Date: 2026-09-29 15:31:56.969608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e7c765008b'
down_revision: Union[str, Sequence[str], None] = '23b2f4cd13f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_citizens_world_name', 'citizens', ['world_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_citizens_world_name', table_name='citizens')
    # ### end Alembic commands ###
